### ISSUE TITLE
Error while running bash farmvibes-ai.sh setup command.

### ISSUE THREAD

**Issue by nitinya9av** [microsoft/farmvibes-ai#103]
I am using ubuntu 20.04

![Screenshot from 2023-06-04 08-44-16](https://github.com/microsoft/farmvibes-ai/assets/58939117/84be626f-bea7-444f-b79f-80205208369f)

**Comment by nitinya9av** [comment]
Is something wrong with these lines 41,42 and 245 of cluster-function.sh file as showing on error description. @renatolfc @rafaspadilha @py5gol @lonnes
![Screenshot from 2023-06-09 13-51-26](https://github.com/microsoft/farmvibes-ai/assets/58939117/6a5c3f86-ceb3-4b5d-a594-45631dcfb37d)
![Screenshot from 2023-06-09 13-51-55](https://github.com/microsoft/farmvibes-ai/assets/58939117/35ebc1da-eb7a-4795-a6c9-bb053b3e8a85)

**Comment by rafaspadilha** [comment]
Hi, @nitinya9av. We have just released a new version of FarmVibes.AI, which updated the setup process. Please, could you test it and check if you are still having issues?

Make sure that you [install all the dependencies as explained in our QuickStart guide](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html#optional-installing-software-dependencies) prior to setting up your cluster.

**Comment by nitinya9av** [comment]
Hi, @rafaspadilha I Am trying to setup new version but get this error on running "farmvibes-ai local setup" command,
![Screenshot from 2023-09-20 22-55-07](https://github.com/microsoft/farmvibes-ai/assets/58939117/d5fa1b2b-e387-4ef6-8a1d-741a30127a3e)

**Comment by nitinya9av** [comment]
Hello, @rafaspadilha , I want to mention one more thing that before running "farmvibes-ai local setup", i got warning message while running "bash ./resources/vm/setup_farmvibes_ai_vm.sh"


![Screenshot from 2023-09-23 11-37-11](https://github.com/microsoft/farmvibes-ai/assets/58939117/2952e74f-acf4-4474-90db-611e2a06059c)

**Comment by famarques** [comment]
> Hello, @rafaspadilha , I want to mention one more thing that before running "farmvibes-ai local setup", i got warning message while running "bash ./resources/vm/setup_farmvibes_ai_vm.sh"
> 
> ![Screenshot from 2023-09-23 11-37-11](https://user-images.githubusercontent.com/58939117/270093275-2952e74f-acf4-4474-90db-611e2a06059c.png)

adding the directory to PATH and running `pip install --upgrade python-dateutil` seems worked for me

**Comment by nitinya9av** [comment]
Thank You!!! @famarques adding the directory to PATH and running `pip install --upgrade python-dateutil` seems worked for me also, but @rafaspadilha I'm getting error at last after running cluster.


![Screenshot from 2023-10-14 15-45-39](https://github.com/microsoft/farmvibes-ai/assets/58939117/a8a53cbf-7061-4b64-a15b-6887ea177a34)

**Comment by rafaspadilha** [comment]
Hi, @nitinya9av. The error is not very informative, unfortunately. We've seen similar issues when the storage is full, could you share the output of `df -kh`, please?

**Comment by nitinya9av** [comment]
> Thank You!!! @famarques adding the directory `/home/beats/.local/bin ` to PATH and running `pip install --upgrade python-dateutil` seems worked for me also, but @rafaspadilha I'm getting error at last after running `farmvibes-ai local setup` .
> 
> ![Screenshot from 2023-10-14 15-45-39](https://user-images.githubusercontent.com/58939117/275307303-a8a53cbf-7061-4b64-a15b-6887ea177a34.png)

This error was solved by increaseing the storage.

**Comment by nitinya9av** [comment]
Hello, @rafaspadilha. After increasing storage, and running `farmvibes-ai local setup` getting an error
![Screenshot from 2023-10-21 14-34-45](https://github.com/microsoft/farmvibes-ai/assets/58939117/98bedba5-f499-4853-ae97-69a3106cf73c)


Here is the Output of `df -kh`

![Screenshot from 2023-10-21 14-35-29](https://github.com/microsoft/farmvibes-ai/assets/58939117/5dc54b82-aa75-4b6e-ba96-61fd862922c6)

**Comment by rafaspadilha** [comment]
Could you provide the output of `kubectl get events` and `kubectl get pods`, please?

**Comment by nitinya9av** [comment]
Running command `kubectl get events` from root directory of the folder, getting an error `Command 'kubectl' not found, but can be installed with: sudo snap install kubectl` is that mean, i have to install it manually (Not included in farmvibes local setup).

![Screenshot from 2023-10-23 23-13-04](https://github.com/microsoft/farmvibes-ai/assets/58939117/88ba714d-f244-4467-bd0e-561b3bf7977c)

**Comment by nitinya9av** [comment]
After added `/home/.config/farmvibes-ai` to PATH, but getting same error, is there anything that i'm doing wrong.
This is the output of `echo $PATH`
![Screenshot from 2023-10-24 00-08-13](https://github.com/microsoft/farmvibes-ai/assets/58939117/b0012605-cc2a-46a9-a13b-7d3df95e5827)

**Comment by renatolfc** [comment]
The `$HOME` env var should have expanded to your user account's home path. From your screenshot, I might infer (assuming a default home path) it should point to `/home/beats`, not `/home`.

In other words: `export PATH=/home/beats/.config/farmvibes-ai:$PATH` should have been the correct command.

**Comment by nitinya9av** [comment]
Thank You!!! @renatolfc.
Here is the output of `kubectl get events` and `kubectl get pods` @rafaspadilha.
![Screenshot from 2023-10-24 00-19-52](https://github.com/microsoft/farmvibes-ai/assets/58939117/c08ecde5-256c-4201-986d-9be0b6bb597c)

**Comment by renatolfc** [comment]
Thanks for sharing the logs @nitinya9av. So, it appears that the cache and dataops deployments that had failed on https://github.com/microsoft/farmvibes-ai/issues/103#issuecomment-1773727453 eventually succeeded.

But the worker deployments are still failing.

The worker image should be available (and doing a `docker manifest inspect mcr.microsoft.com/farmai/terravibes/worker:2023.09.05` should show that).

Do you mind trying to restart the worker pods with `kubectl delete pod -l app=terravibes-worker` or `kubectl rollout restart deployment terravibes-worker`?

Also, keep in mind that the worker image is huge (we're working on reducing that) and due to that, the initial cluster setup might fail if the image is not downloaded within 1h.

**Comment by nitinya9av** [comment]
@renatolfc. How big is worker image, I'm using high speed internet but it failed to download the image within a hour, is there any other way by which i can continue downloading it after an hour.

![Screenshot from 2023-10-24 02-09-10](https://github.com/microsoft/farmvibes-ai/assets/58939117/14f3d02f-eacf-413f-9063-868339de3c3f)

**Comment by nitinya9av** [comment]
@renatolfc and @rafaspadilha I tryed to redownload worker image by running command `farmvibes-ai local update` but it destroyed the previous image and start downloading new from start, Is there no command by which I can continue downloading it?

**Comment by renatolfc** [comment]
Hello @nitinya9av,

In a local deployment, we use two main tools to manage the cluster:
 * `k3d`, to create the local cluster using your docker installation
 * `terraform`, to configure the cluster and deploy the farmvibes-ai services to the cluster

When we get to the service deployment step, what we do is:
 1. We apply the configuration of the services to the cluster
 2. We wait until all services are up to return, waiting for up to 1h

The download of the images themselves is made by the kubernetes infrastructure within the k3d cluster, and the 1h timer is expiring in your local install while waiting for the download to complete.

In general, as long as your internet connection is stable, kubernetes would eventually complete the download. From the logs [you shared above](https://github.com/microsoft/farmvibes-ai/issues/103#issuecomment-1775829482), it appears kubernetes gave up on downloading the images, especially given that resolving the `mcr.microsoft.com` domain name failed, indicating a DNS failure on the client end.

Deleting the pods [with the commands I shared above](https://github.com/microsoft/farmvibes-ai/issues/103#issuecomment-1775840231) should be enough to encourage kubernetes to redownload the images.

Due to the size of the images and to the time it takes to download them, we cache the images under `~/.cache/farmvibes-ai/registry`. As of now, the registry cache takes 13GB in my machine. Due to the cache, if you downloaded images fully once, redeploying a cluster should be much faster, as the download would be, essentially, a local copy.

There is one thing you could do to try and help kubernetes to speed up the download. You could manually pull the image with `docker pull mcr.microsoft.com/farmai/terravibes/worker:2023.09.05`, and then [import the image](https://k3d.io/v5.0.3/usage/commands/k3d_image_import/) into your k3d cluster.

You could even try doing a `k3d image import mcr.microsoft.com/farmai/terravibes/worker:2023.09.05`, although I'm not sure the download would work directly. (As with `kubectl`, you need to add the farmvibes-ai directory to your `PATH` env var for the `k3d` command to work.)

**Comment by nitinya9av** [comment]
I am trying to download the worker image using `k3d image import mcr.microsoft.com/farmai/terravibes/worker:2023.09.05` but getting an error `FATA[0001] failed to get cluster k3s-default: No nodes found for given cluster`

**Comment by renatolfc** [comment]
You have to pass the cluster name as an argument to `-c`. You can get your current cluster name by doing a `k3d cluster list`. The default name is `farmvibes-ai-$USERNAME`, so for your account it should be `farmvibes-ai-beats`.

**Comment by nitinya9av** [comment]
@renatolfc. After passing cluster name as argument `k3d image import mcr.microsoft.com/farmai/terravibes/worker:2023.09.05 -c farmvibes-ai-beats` getting an error `ERRO[0001] Failed to import image(s) into cluster 'farmvibes-ai-beats': no valid images specified`

![Screenshot from 2023-10-24 23-49-05](https://github.com/microsoft/farmvibes-ai/assets/58939117/f5167821-492b-4284-bfb6-3aa8ba48f180)

**Comment by renatolfc** [comment]
The it appears `k3d image import` does not support importing directly from a remote container registry. You will have to do a `docker pull` followed by a `docker export` and, finally, a `k3d image import` pointing to the image you exported with `docker export`.

**Comment by nitinya9av** [comment]
What are the commands for `docker export` and `k3d image import` after downloading docker image with `docker pull mcr.microsoft.com/farmai/terravibes/worker:2023.09.05`

**Comment by nitinya9av** [comment]
@renatolfc, i changed my network to stable high speed, now my setup was successful, cluster is created and REST API is running on localhost but when i run helloworld workflow its world map is not shown on REST API link and also when i am trying to access REST API documentation on `http://localhost:30000/v0/docs` it is showing this






![Screenshot from 2023-11-18 15-40-16](https://github.com/microsoft/farmvibes-ai/assets/58939117/08b7526e-050b-451e-b839-a94e49cc2047)





![Screenshot from 2023-11-18 15-55-44](https://github.com/microsoft/farmvibes-ai/assets/58939117/0b23690d-4fc5-415d-be5a-a0ff426474a5)






![Screenshot from 2023-11-18 15-45-28](https://github.com/microsoft/farmvibes-ai/assets/58939117/92f4e134-a80c-4975-801c-6ee3c6fbee4d)

**Comment by rafaspadilha** [comment]
Thanks, @nitinya9av, for reporting that the setup worked correctly. 

When you run `python -m vibe_core.farmvibes_ai_hello_world`, the FarmVibes.AI cluster will invoke the `hello_world` workflow and report that the run has finished successfully. The world map will be stored as an asset of the `VibeWorkflowRun`, whose id is printed by the script. In our repo, we provide the [hello_world notebook](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/helloworld.ipynb) that calls the same workflow and visualize the output.

I saw that you opened a new issue to discuss the bug with the REST-API documentation (#131). Thank you for that. I will close this issue for now and continue the discussion on the new issue.

**Comment by Tejashreenk** [comment]
What is the file path of the Image? When you say that the world map will be stored as an asset of the VibeWorkflowRun, where do I find VibeWorkflowRun?

**Comment by rafaspadilha** [comment]
Hi, @Tejashreenk. Please, for more visibility from the team and to help us address your issue quickly, we kindly ask that you open a new issue instead of commenting on closed issues. 

Please refer to the [hello world notebook](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/helloworld.ipynb) for an example of how to visualize the output raster. The [notebook directory in our repo](https://github.com/microsoft/farmvibes-ai/tree/main/notebooks) also has several examples on how to interact with the outputs of our workflows.

Feel free to open a new issue if the problem persists.

**Comment by click2cloud-SanchitG** [comment]
how to install farmvibes-ai cluster other than k3d.
