### ISSUE TITLE
Error while setup remote cluster on AKS :-  Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.26.3 is not supported in this region(eastus). 

### ISSUE THREAD

**Issue by click2cloud-kaliram** [microsoft/farmvibes-ai#130]
Geeting AgentPoolK8sVersionNotSupported error while setup remote cluster on AKS :-  Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.26.3 is not supported in this region.

![image](https://github.com/microsoft/farmvibes-ai/assets/70700042/958d6725-f13a-488e-9ef2-380a4d5ed3cf)

**Comment by brsilvarec** [comment]
Hi @click2cloud-kaliram, Thanks for using FarmVibes.AI

I generally use eastus as region to create a new FarmVibes AKS cluter. The command I use is the following.

```bash
farmvibes-ai remote setup --verbose --resource-group <your_resource_group> --cluster-name <your_cluster_name> --cert-email <your_selected_email> --region <your_region>
```

In my case, I use `<your_region>` as `eastus` and it works. 

Can you please share the command you used to create the cluster?

**Comment by renatolfc** [comment]
Hello @click2cloud-kaliram, it turns out that Azure stopped supporting the kubernetes version we were using.

While we don't do a new release, to fix this issue, please edit the [kubernetes.tf](https://github.com/microsoft/farmvibes-ai/blob/main/src/vibe_core/vibe_core/terraform/aks/modules/infra/kubernetes.tf#L9) file and change the `1.26.3` version to `1.27.7`.

Thanks.

**Comment by rafaspadilha** [comment]
@click2cloud-kaliram, we made a new release #140 that updated the version of kubernetes to `1.27.7`. This should fix the issue you are seeing.

Please, let us know if the problem persists.

**Comment by click2cloud-kaliram** [comment]
@rafaspadilha thanks issue fixed
