### ISSUE TITLE
Install ERROR during pip install ./src/vibe_core

### ISSUE THREAD

**Issue by PeterMHammond** [microsoft/farmvibes-ai#138]
I've followed the instructions from the [Quickstart](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html#quickstart) installing on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64) without issue and have also restarted the shell after setting up the prerequisites.  
[Install the FarmVibes.AI cluster](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html#install-the-farmvibes-ai-cluster)
Running the pip install ./src/vibe_core seems to fail with UNKNOWN and the following steps fail afterwards.
```
pip install ./src/vibe_core
Defaulting to user installation because normal site-packages is not writeable
Processing ./src/vibe_core
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=fb3d3a7e91bd9188c9d791478658caa2d384d53404a85f1e188a74c16165445b
  Stored in directory: /tmp/pip-ephem-wheel-cache-04bho5rx/wheels/1c/40/b1/38e9251b90881c4df413cc556ecbcc2c25ea013be6f7f9df69
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

**Comment by renatolfc** [comment]
Hello,Can you try upgrading pip with “pip install --upgrade pip”?—Renato Luiz de Freitas CunhaOn 3 Jan 2024, at 13:17, Peter M. Hammond ***@***.***> wrote:﻿[microsoft/farmvibes-ai] Install ERROR during pip install ./src/vibe_core (Issue #138)I've followed the instructions from the Quickstart installing on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64) without issue and have also restarted the shell after setting up the prerequisites.Install the FarmVibes.AI clusterRunning the pip install ./src/vibe_core seems to fail with UNKNOWN and the following steps fail afterwards.pip install ./src/vibe_core
Defaulting to user installation because normal site-packages is not writeable
Processing ./src/vibe_core
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=fb3d3a7e91bd9188c9d791478658caa2d384d53404a85f1e188a74c16165445b
  Stored in directory: /tmp/pip-ephem-wheel-cache-04bho5rx/wheels/1c/40/b1/38e9251b90881c4df413cc556ecbcc2c25ea013be6f7f9df69
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0

**Comment by PeterMHammond** [comment]
> Hello, Can you try upgrading pip with: pip install --upgrade pip

Was using 22.0.2, Successfully installed pip-23.3.2
That appears to have been the issue, and the install is proceeding as anticipated.
Thank you for your quick assistance!
