### ISSUE TITLE
How to choose? Local setup on VM vs Remote AKS cluster?

### ISSUE THREAD

**Issue by chetan2309** [microsoft/farmvibes-ai#143]
### Topic

FarmVibes.AI setup, Local cluster, Remote (AKS) cluster

### Ask away!

Hi Team,

I would like to get clarity purely from cost perspective what and how to choose! What are cost implications of setting an Azure VM and then do the installation vs setting up a remote cluster?

- I initially thought that AKS would be cheaper but seeing the cost in resource group made me believe that probably they would cost almost same.
- On an Azure VM with installation I can run notebooks and connect via my local machine via port forwarding. I believe I can’t do the same on Remote AKS setup! Please guide.
- What’s the situation where you would choose Azure AKS setup over VM setup? 

Thanks,
Chetan

**Comment by renatolfc** [comment]
Hello @chetan2309, thanks for your question!

 - If memory serves, an empty VM using the [default configuration](https://github.com/microsoft/farmvibes-ai/blob/main/resources/vm/farmvibes_ai_vm.bicep) on Azure [should be cheaper](https://cloudprice.net/vm/Standard_D8s_v3?timeoption=month) than an AKS cluster.
 - When you setup an AKS cluster, FarmVibes.AI gives you a public endpoint you can connect to. That endpoint is open by default, so you point your notebooks to it and run your workflows directly. (If you have security requirements, we encourage you to restrict access from the Azure portal itself.)

In general, you'd want to use a VM for development and experimentation and once you get into "steady state" of execution, you should probably migrate to AKS, as that'll allow for faster workflow execution and automatic storage scaling.

AKS has two other advantages as well: it is inherently multi-user (and multi-admin), and storage costs scale much slower than those of the VMs, because on AKS the asset storage is backed by Azure Blobs, whereas the VM uses HDDs or SSDs.

**Comment by chetan2309** [comment]
@renatolfc - thanks for your detailed explanation on this.
