### ISSUE TITLE
How to deploy Farm vibes on Existing on-premises OpenShift or Kubernetes cluster

### ISSUE THREAD

**Issue by click2cloud-kaliram** [microsoft/farmvibes-ai#150]
### Ask away!

"When executing the Farmvibes local setup command, it automatically generates its own k3d cluster. Is it possible to manually deploy Farmvibes on an existing Kubernetes or OpenShift cluster , could you provide guidance along with the deployment YAML file?"

**Comment by renatolfc** [comment]
Hello @click2cloud-kaliram, unfortunately, this is not supported by our current code, and I'm afraid we don't have the bandwidth to implement such a feature (I would be willing to review a PR that added support for that, though).

The main reason we don't support this is because we can't know how kubernetes node pools and persistent volumes would work in arbitrary clusters.

Although unsupported by the scripts, if you look at the [`setup`](https://github.com/microsoft/farmvibes-ai/blob/8f6fb59e755ab5301ae615cb4bd9eac89598ef6f/src/vibe_core/vibe_core/cli/local.py#L225) function, you will see that we use Terraform to ensure a local cluster is setup. (We have similar code for the AKS clusters, but that code is a bit more complex.)

If you are proficient with TerraForm, you can try applying [the scripts](https://github.com/microsoft/farmvibes-ai/tree/main/src/vibe_core/vibe_core/terraform) to your existing cluster to deploy FarmVibes.AI to it.

You will probably have to edit the terraform files to suit your cluster, but again, we can't provide support with that.

You would have better luck setting up an AKS cluster specifically for FarmVibes.AI.
