### ISSUE TITLE
Issue with running spaceeye workflow: 'data_ingestion/spaceeye/spaceeye' 

### ISSUE THREAD

**Issue by ajinkyapol** [microsoft/farmvibes-ai#167]
### In which step did you encounter the bug?

Workflow execution

### Are you using a local or a remote (AKS) FarmVibes.AI cluster?

Local cluster

### Bug description

While running 'data_ingestion/spaceeye/spaceeye' workflow, it can execute all the tasks related to sentinel 2 data but when it reaches for tasks related to sentinel 1 data it fails with following error related to pc_sub_key:

'RuntimeError: Failed to run op download_sentinel1 in workflow run id d14f7207-0017-4f54-83d3-da98f273de0c for input with message id 00-d14f720700174f5483d3da98f273de0c-802aa0c10bf15114-01. Error description: <class \'RuntimeError\'>:  ValueError(\nValueError: Could not retrive secret pc-sub-key from Dapr.\n Error message <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.INTERNAL\n\tdetails = "failed getting secret with key pc-sub-key from secret store kubernetes: secrets "pc-sub-key" not found"\n\tdebug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50001 {grpc_message:"failed getting secret with key pc-sub-key from secret store kubernetes: secrets "pc-sub-key" not found", grpc_status:13, created_time:"2024-05-09T06:37:45.355106606+00:00"}"\n>\n.'

**Comment by rafaspadilha** [comment]
Hi, @ajinkyapol. Since our latest release, the Planetary Computer API key became a required parameter to download Sentinel-1 data. You can either pass it as a parameter when running the workflow, or add it to the cluster with the `add-secret` command. 

The error that you see `"failed getting secret with key pc-sub-key from secret store kubernetes: secrets "pc-sub-key" not found"` happens because no value was passed as the `pc_key` parameter, and we use the default value which checks for the `pc-sub-key` secret in the cluster.

For more information on adding secrets to the cluster and using them in workflows, please refer [to our documentation](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/SECRETS.html).

Finally, I just noticed that the workflow documentation for the `pc_key` parameter is outdated, saying it is an "Optional" parameter. I will update this for the next release.

**Comment by rafaspadilha** [comment]
Closing this issue for now. @ajinkyapol, please, feel free to reopen it if you still have issues with this.
