### ISSUE TITLE
Unable to visualize the raster 

### ISSUE THREAD

**Issue by ghost** [microsoft/farmvibes-ai#37]
Dear FarmVibes-Ai team, 

 I am unable to visualize the output while running the "Hello World.Ipynb" via python client .
Moreover, I am unable to display the output while runing code  directly on server.
 Anyone could assist me in this regard.

**Comment by brsilvarec** [comment]
Hi @itshassan12, 

Thanks for trying FarmVibes.AI. I will be glad to help you with this. In order to provide you a more precise help, I will ask you a few questions.
    
1. What is underlying infrastructure you are running FarmVibes.AI cluster? Are you using a dedicated VM for it or some existing linux VM?
2. What is the output of this command  `bash farmvibes-ai.sh status`? In a working deployment, you should see something like this.
```bash
bash farmvibes-ai.sh status
farmvibes-ai   1/1       0/0      true
FarmVibes.AI REST API is running at http://172.23.0.3:30000
```
3. Can you post the output of your jupyter notebook when you issue the problematic command?

Hope I can identify what is going on with your inputs....
Best Regards

**Comment by renatolfc** [comment]
The original author of this issue has deleted their account on GitHub.

I'm closing this issue.

For a terminal-based way of visualizing the output of the helloworld workflow, installing the `caca-utils` package on Debian/Ubuntu will give you the `img2txt` command.

If you have the `img2txt` command, you can view TIFFs in the terminal itself with `find ~/.cache/farmvibes-ai/data -type f -name '*.tif' -exec img2txt {} \;`.

Doing so in my terminal yields:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/734653/219428592-a72441ca-2c89-4f64-970b-4dfcecf894bd.png">
