### ISSUE TITLE
Error in running notebook land_degradation.ipynb

### ISSUE THREAD

**Issue by click2cloud-sagarB** [microsoft/farmvibes-ai#41]
Dear Farmvibes Team,
While running workflow "farm_ai/land_degradation/landsat_ndvi_trend" in land_degradation.ipynb notebook  the task "trend.chunked_linear_trend.linear_trend"  did not succeed and encountered an error  **"missing 1 required positional argument "**
I have attached the screenshot of task which was failed along with its log for better understanding. 

![1 crop](https://user-images.githubusercontent.com/115791095/218697376-dc81ef98-2778-4fd4-ad52-259a53f3abec.jpg)

![2](https://user-images.githubusercontent.com/115791095/218697421-79684fc2-ac35-4700-8e0d-d9a0a0d041b1.JPG)

**Comment by rafaspadilha** [comment]
Hi, @click2cloud-sagarB. Thank you for raising this issue.

We've recently added a new parameter to `RasterChunk` class, but forgot to include it in the `linear_trend` op that creates a `RasterChunk`. Unfortunately this slipped past our tests. 

We have already opened a PR and it should be fixed in the next release.
Thank you and the team for opening the issue.

**Comment by rafaspadilha** [comment]
Closing this issue due to the fix in PR #44 .
Let us know if you still find any issues while running.
