### ISSUE TITLE
please help deepmc setting

### ISSUE THREAD

**Issue by ziwonSeo-lab** [microsoft/farmvibes-ai#68]
Could you please confirm if setting chunk_size = 2620, ts_lookback = 240, and total_models = 130 would be appropriate for predicting 130 hours using DeepMC, with 240 data points in the lookback window and a 60-minute frequency?
 Additionally, I would like to know how the value of 524 is calculated for predicting 24 hours using a frequency of 60 minutes.

thank you!

**Comment by peeyush-kumar** [comment]
@ziwonSeo-lab The chunk size captures the length at which wavelets can start picking up long scale weather patterns. For now it is set through experimental tuning, where we found that approximately a 3 week period picks up those long scale patterns for intra day predictions.

In order to predict for 130 hours, there are more parameters to be configured for effective prediction. Out-of-the-box DeepMC is configured for micro-climate predictions for short time predictions - typically for tasks <96 hour prediction & 60-min resolution. You could just start by what you suggested and see if the results meets your requirement. One thing to keep in mind is that higher the chunk size, smaller the data for training. So if you are limited on data, I would not recommend increasing the chunk size.

For other parameter configuration:
The network parameters for inner layers is a function of frequency X lookahead. For predicting 130 hours at 60 minute frequency some of the inner layers might need to be edited. Specifically the final layer of the encoder which is the layer that concatenates inputs from various scales and the decoder layers. Both those layers need to be expanded to allow the network to have enough capacity to encode longer temporal windows. I do not have a direct answer to what the exact number should be as that will be determined experimentally.
