### ISSUE TITLE
running `bash farmvibes-ai.sh update` gives me this error

### ISSUE THREAD

**Issue by lonnes** [microsoft/farmvibes-ai#85]
running `bash farmvibes-ai.sh update` gives me this error

![image](https://user-images.githubusercontent.com/733563/231321794-b6356c65-3f3f-4e22-a8c4-02f652648de7.png)

Plan: 16 to add, 0 to change, 0 to destroy.
module.kubernetes.kubernetes_namespace.kubernetesdaprnamespace: Creating...
module.kubernetes.kubernetes_persistent_volume.user_storage_pv: Creating...
module.kubernetes.helm_release.redis: Creating...
module.kubernetes.helm_release.rabbitmq: Creating...
╷
│ Error: namespaces "dapr-system" already exists
│
│   with module.kubernetes.kubernetes_namespace.kubernetesdaprnamespace,
│   on modules/kubernetes/dapr.tf line 1, in resource "kubernetes_namespace" "kubernetesdaprnamespace":
│    1: resource "kubernetes_namespace" "kubernetesdaprnamespace" {
│
╵
╷
│ Error: persistentvolumes "user-storage-pv" already exists
│
│   with module.kubernetes.kubernetes_persistent_volume.user_storage_pv,
│   on modules/kubernetes/persistentvolume.tf line 1, in resource "kubernetes_persistent_volume" "user_storage_pv":
│    1: resource "kubernetes_persistent_volume" "user_storage_pv" {
│
╵
╷
│ Error: cannot re-use a name that is still in use
│
│   with module.kubernetes.helm_release.rabbitmq,
│   on modules/kubernetes/rabbitmq.tf line 1, in resource "helm_release" "rabbitmq":
│    1: resource "helm_release" "rabbitmq" {
│
╵
╷
│ Error: cannot re-use a name that is still in use
│
│   with module.kubernetes.helm_release.redis,
│   on modules/kubernetes/redis.tf line 1, in resource "helm_release" "redis":
│    1: resource "helm_release" "redis" {

_Originally posted by @richstep in https://github.com/microsoft/farmvibes-ai/discussions/83#discussioncomment-5587048_

**Comment by renatolfc** [comment]
This is happening because we've introduced TerraForm to deploy services in our cluster, but it seems there isn't any TerraForm state in @richstep's environment, probably due to an old cluster.

The easiest path forward would be to recreate the cluster, restoring workflow state at the end of the process.

Another, more error prone, solution would be to call the now-deprecated `farmvibes-ai.sh update-images`.

We apologize for the inconvenience, but I'm not sure we have a way of building terraform state from an existing cluster. I'll investigate.
